### ISSUE TITLE
aa doesn't change

### ISSUE THREAD

**Issue by GameChaos** [squeek502/Squake#14]
airacceleration doesn't seem to change when changing  D:airAccelerate in the config file from 14 to 9999999

**Comment by squeek502** [comment]
What are you expecting the results to be? Quake movement is kind of weird in that the air acceleration value pretty much only controls how smoothly you need to move your mouse to *maintain* speed--it does not affect how quickly you *gain* speed. With an air acceleration value of 999999 it would mean you can move your mouse like crazy in any direction and pretty much never lose speed because of it.

If you're looking to gain speed faster, you will want to change `maxAirAccelerationPerTick` instead.

**Comment by GameChaos** [comment]
the max turning speed feels the same on 999999aa as 14aa

**Comment by squeek502** [comment]
There is definitely a difference. The two gifs below are doing roughly the same thing, but have completely different outcomes. Note that I turned up `maxAirAccelerationPerTick` to `0.1` for these demonstrations, because the difference is more noticeable at higher speeds.

With 14 airaccelerate, you lose all speed when trying to change directions very quickly:
![2017-10-03 04-56-04 00h00m19 250s-00h00m24 231s mp4](https://user-images.githubusercontent.com/2389051/31124322-dd7f9740-a7f8-11e7-891c-d8786f5e5c75.gif)

With 999999 airaccelerate, you keep a lot of speed when trying to change directions very quickly:
![2017-10-03 04-55-22 00h00m09 221s-00h00m14 195s mp4](https://user-images.githubusercontent.com/2389051/31124329-e5d12116-a7f8-11e7-9de6-12fab67180bb.gif)
